/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ccariou <ccariou@hive.fi>                  +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/09/07 09:28:01 by ccariou           #+#    #+#             */
/*   Updated: 2022/09/16 17:47:29 by ccariou          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

//la bite de raoul est abberante

#include <stdio.h>
#include "../includes/filler.h"

/*int	valid_map(t_info *info)
{
	//what makes a map viable i : column, row and two starting point//
	if map have no column or grid
		return error;
	if map dont have starting point for p1 && p2
		return error;
	//CAN COMBINE TWO PREVIOUS STATEMENT
	else
		return ok;
}

void	create_map(t_info *info)
{
	return ;
}
*/

/*
int	player_info(t_info *info)
{
	who is player 1;
	who is player 2;
}
*/

int	main(int argc, char **argv)
{
	//int		check;
	//int		valid;
	t_info	info;
//	char	*line;

//	line = NULL;
//	if piece free piece
	if (!argc || !argv)
		ft_printf("oalala no argc");
	/* PROBABLY NOT NEEDED 
	if (argc != 8)
	{
		return (1);
		printf("usage : ./filler_vm -p1 player -p2 player -v -f map");
	}
	*/ 
	//info.line = ft_strdup(*argv);
	/*if (line == NULL)
	{
		ft_printf("en slip sur la banquise");
		return (1);
	}
	*/
	player_info(&info);
	fprintf(stderr, "enemy = %c\n", info.enemy);
	map_info(&info);
//	pieces_info();
//	check_move(&info);
/*	if (valid_map)
	get_info;
		ok;
	create_map;
	//board generated by the vm
	player_info;
	piece_info;
	*/
	return (0);
}

