/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ccariou <ccariou@hive.fi>                  +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/09/07 09:28:01 by ccariou           #+#    #+#             */
/*   Updated: 2022/09/15 10:16:30 by ccariou          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

//la bite de raoul est abberante

#include <stdio.h>
#include "../includes/filler.h"

/*int	valid_map(t_info *info)
{
	//what makes a map viable i : column, row and two starting point//
	if map have no column or grid
		return error;
	if map dont have starting point for p1 && p2
		return error;
	//CAN COMBINE TWO PREVIOUS STATEMENT
	else
		return ok;
}

void	create_map(t_info *info)
{
	return ;
}
*/
static int	player_info(t_info *info)
{
	char	*stdo;
	int		player;

	stdo = NULL;
//	get_next_line(0, &stdo);
	get_next_line(0, &stdo);
	ft_printf("stdo == %s\n", stdo);
	player = ft_atoi(&stdo[10]);
	if (player == '1')
		info->player = 'o'; 
	else if (player == '2')
		info->player = 'x'; 
	else
		return (1);
//	fprintf(stderr , "info->player = %d\n", info->player);
//	fprintf(stderr , "tu as un gros loulou\n");
	return (0); //tutto va bene need to make error checks ?
}

static int	map_info(t_info *info)
{
	char	*stdo;
	int		i;

	stdo = NULL;
	i = 0;
	get_next_line(0, &stdo);
	fprintf(stderr , "tu as un grosse map\n\n");
	fprintf(stderr, "mapinfo stdo ==  %s\n\n", stdo);
	info->row  = ft_atoi(&stdo[8]);
	fprintf(stderr , "info->row= %d\n", info->row);
	info->col = ft_atoi(&stdo[11]);//adjust stdo to numblen
	fprintf(stderr , "info->col= %d\n", info->col);
	get_next_line(0, &stdo);
	info->map = malloc((info->row + 1) * sizeof(int));
	while (i < info->row)
	{
		get_next_line(0, &stdo);
		info->map[i] = ft_strsub(stdo, 4 , info->row);
		fprintf(stderr, "mapinfo stdo ==  %s\n\n", info->map[i]);
		i++;
	}
	return (0); //tutto va bene need to make error checks ?
	// can probably check with stdo[0] == "P"
}

static int	pieces_info(t_info *info)
{
	char	*line;
	int		i;
//	int 	col;
	int		size;
	int		row;

	line = NULL;
	i = 0;
//	col = info->col;

	//*line =	get_next_line(0, &line);
	//fprintf(stderr, "pieces_info stdo ==  %s\n\n", line);
	get_next_line(0, &line);
	fprintf(stderr, "piece_info stdo ==  %s\n\n", line);
	info->piecerow = ft_atoi(&line[6]);
	fprintf(stderr , "info->piecerow= %d\n", info->piecerow);
	info->piececol= ft_atoi(&line[8]);//adjust stdo to numblen
	fprintf(stderr , "info->piececol= %d\n", info->piececol);
	row = info->piecerow;
	size = row;
	info->piece = malloc((info->piecerow * info->piececol) * sizeof(int));
	while (i < size)
	{
		fprintf(stderr , "tu as un gros piece mon loulou\n\n");
		get_next_line(0, &line);	
		fprintf(stderr, "piece_info stdo ==  %s\n\n", line);
		info->piece[i] = ft_strdup(line);
		// check to remove the row number
	//	fprintf(stderr , "info->piece = %s\n", info->piece[i]);
		i++;
	}
	i = 0;
	while (i < size)
	{
		fprintf(stderr , "info->piece = %s\n", info->piece[i]);
		i++;
	}
	/*
	while (stdo[0] != "*" || stdo[0] != ".")
		get_next_line(0, &stdo);
	*/
	return (0); 
}

/*
int	player_info(t_info *info)
{
	who is player 1;
	who is player 2;
}
*/

int	main(int argc, char **argv)
{
	//int		check;
	//int		valid;
	t_info	info;
//	char	*line;

//	line = NULL;
//	if piece free piece
	if (!argc || !argv)
		ft_printf("oalala no argc");
	/* PROBABLY NOT NEEDED 
	if (argc != 8)
	{
		return (1);
		printf("usage : ./filler_vm -p1 player -p2 player -v -f map");
	}
	*/ 
	//info.line = ft_strdup(*argv);
	/*if (line == NULL)
	{
		ft_printf("en slip sur la banquise");
		return (1);
	}
	*/
	player_info(&info);
	map_info(&info);
	pieces_info(&info);
/*	if (valid_map)
	get_info;
		ok;
	create_map;
	//board generated by the vm
	player_info;
	piece_info;
	*/
	return (0);
}

